### ISSUE TITLE
SpatialRecordHits not iterating

### ISSUE THREAD

**Issue by peterneubauer** [neo4j-contrib/spatial#106]
https://github.com/neo4j/spatial/commit/7b37c2bf05b94152964ee70e75e09974c367d84d shows that despite hits being found, they are not propagated to the result. Needs to be fixed.

**Comment by jamilabreu** [comment]
+1 :)

**Comment by ishare** [comment]
+1

**Comment by jocarpt** [comment]
+1 :)

**Comment by Miamoto-Musashi** [comment]
+1

**Comment by ehx-v1** [comment]
to all those who commented "+1", that's what the "Add reaction" button actually is for ;-)

**Comment by craigtaverner** [comment]
This bug-report seems to be related specifically to the old pre-3.0 IndexProvider API (accessible through the REST API). The REST API is deprecated and entirely removed. The replacement procedures have been the only option since 3.0. If anyone has seen a similar bug in the procedures, please report it in a new bugreport with details on exactly how to reproduce the bug.
