### ISSUE TITLE
3d spatial modelling and query

### ISSUE THREAD

**Issue by ghost** [neo4j-contrib/spatial#155]
Needing for many engineering projects...

**Comment by metanomy** [comment]
Here's exactly what I'd like to do: store and calculate over CityGML. The easiest way to do this is might be to refactor the 3DCityDB PostGIS Importer/Exporter (https://github.com/3dcitydb/importer-exporter-postgis) to conform to Neo4J spatial structures.

**Comment by muzbox** [comment]
Did any work ever begin on 3D spatial?

I have a use case of wanting to store and analyse geological data in Neo4j. This data requires analysis in 3D as the depth component is required for true analysis.

**Comment by craigtaverner** [comment]
Sorry for the slow reply. There has indeed been some 3D work. Two projects, but neither of which are in this spatial library (yet).

The first is the support for 3D points within the Neo4j database itself. Since version 3.4 (released in the spring of 2018) there are four types of points: 2D cartesian, 3D cartesian, 2G geographic and 3G geographic. Take a look at the documentation at https://neo4j.com/docs/cypher-manual/current/syntax/spatial/ for more details.

There was also a very small community project called `spatial-3d` which aims to support point-in-3d-polygonmesh queries, but is not yet able to do that. It can do point-in-2d-polygon searches, and I hope to expand it to 3D at some point.

My recommendation is to try out the 3D support within Neo4j itself. If that works, great. If not, then open new requests on either of the following projects:

- [Neo4j](https://github.com/neo4j/neo4j) - if what you want is a small addition to the points-only support in Neo4j
- [spatial-3d](https://github.com/craigtaverner/spatial-3d) - if what you want is specifically point-in-3d-polygon-mesh support
- spatial - if you want 3d support together with this library
