### ISSUE TITLE
500 response when adding node to spatial index

### ISSUE THREAD

**Issue by ariieh** [neo4j-contrib/spatial#174]
Am I doing something wrong here? I've been following along [this](https://neo4j-contrib.github.io/spatial/#rest-api-create-a-spatial-index) tutorial and I can create a spatial index, getting back:

```
{
"template"=>"http://localhost:7475/db/data/index/node/users/{key}/{value}",
"provider"=>"spatial",
"geometry_type"=>"point",
"lat"=>"lat",
"lon"=>"lon"
}
```

I then create a node, getting this response:

```
{
"extensions"=>{},
"outgoing_relationships"=>"http://localhost:7475/db/data/node/55/relationships/out",
"labels"=>"http://localhost:7475/db/data/node/55/labels",
"traverse"=>"http://localhost:7475/db/data/node/55/traverse/{returnType}",
"all_typed_relationships"=>"http://localhost:7475/db/data/node/55/relationships/all/{-list|&|types}",
"self"=>"http://localhost:7475/db/data/node/55",
"property"=>"http://localhost:7475/db/data/node/55/properties/{key}",
"outgoing_typed_relationships"=>"http://localhost:7475/db/data/node/55/relationships/out/{-list|&|types}",
"properties"=>"http://localhost:7475/db/data/node/55/properties",
"incoming_relationships"=>"http://localhost:7475/db/data/node/55/relationships/in",
"create_relationship"=>"http://localhost:7475/db/data/node/55/relationships",
"paged_traverse"=>"http://localhost:7475/db/data/node/55/paged/traverse/{returnType}{?pageSize,leaseTime}", "all_relationships"=>"http://localhost:7475/db/data/node/55/relationships/all",
"incoming_typed_relationships"=>"http://localhost:7475/db/data/node/55/relationships/in/{-list|&|types}",
"metadata"=>{"id"=>55, "labels"=>[]}, "data"=>{"lon"=>-76.418495, "lat"=>37.022839}
}
```

But when I try and add the node to the layer, I get a 500. I post to:
http://localhost:7475/db/data/ext/SpatialPlugin/graphdb/addNodeToLayer

With e.g:
`{:layer=>"users", :node=>"http://localhost:7475/db/data/node/55"}`

I notice that my node created response looks a little different from the tutorial example, so I'm wondering if there's a version issue here.

**Comment by jexp** [comment]
Did you create a layer for "add node to layer"? Otherwise "add the node to index function"

**Comment by ariieh** [comment]
@jexp Not quite sure what you're suggesting or what to do here. If I want to run Cypher queries like ``withinDistance:[41.99,-87.67,10.0]``, do I need to create a layer, an index, or both? And what do I need to add the node to? The layer, the index, or both? What should the successive POSTs look like?

**Comment by ehx-v1** [comment]
from what I get, there is more than one error possible:
- first, make sure the layer "users" exists
- next, it must be like:
`{"layer":"users", "node":"http://localhost:7475/db/data/node/55"`
instead of
`{:layer=>"users", :node=>"http://localhost:7475/db/data/node/55"}`
- third, if you're working with WKT, some geometries, like GEOMETRYCOLLECTION or any EMPTY geometry, are not supported (I know that because I started experimenting about the REST API from the Neo4j Browser)

and, by the way, if you start trying out your calls from browser too, don't forget to pre-pend the ":" and to remove the `http://localhost:7475` from the URL (you need it from remote but it makes errors from the browser)

**Comment by craigtaverner** [comment]
The REST API has been deprecated since 3.0. If you have the same problems with the procedures API, please report a new issue.
