### ISSUE TITLE
Slow spatial queries

### ISSUE THREAD

**Issue by Jempan** [neo4j-contrib/spatial#188]
I am using Neo4j 2.2.3 with Spatial 0.15 for a social web application I am building. I have a spatial index geom to where I add all cities and users. For the moment the database contains ~150000 cities and only 3 test users. Unfortunately I am getting very poor performance for all database queries which are touching the spatial index. For example below query to get the nearest users within 50 km takes more than 9 seconds to return the 3 users:

start n=node:geom('withinDistance:[58.0,17.0,50000.0]') MATCH user WHERE user:User return user LIMIT 100

Anything obvious I am doing wrong here? Shouldn't this be much faster?

I read in another thread about plans for native spatial support directly to Neo4j, it would be truly awesome, any news about this?

**Comment by Jempan** [comment]
More about this. I have autocomplete inputs to help the user to pick an existing city in a couple of places in the app. The autocomplete query against the database takes 3-10 s, not very user friendly. Therefore today I was going to try to cache the city names but the database query MATCH (n:City) RETURN n crasches the database and the connection is closed. 

Any suggestion how to accomplish better performance for the autocomplete inputs in a more database friendly way? :)

**Comment by sarmbruster** [comment]
@Jempan the problem here seems to be that the limit doesn't get applied on the index search. So first the spatial index search is performed which might return a huge number of nodes (depending on the distance specified). Using the `MATCH` you basically build a cross product to all the users.
I guess it's a better approach to start off with a very small distance in the spatial query and increase it carefully until you get enough results and match from those to the users. Sounds reasonable?

**Comment by craigtaverner** [comment]
I must second @sarmbruster comments, the lack of any association between 'n' and 'user' in your first query will make a cross product, which can be quite expensive, in your case loading the cities three times instead of once. The second query loading all 150k cities will require that the database have enough memory, so make sure you have it configured correctly.

Regarding spatial index performance, it is worth noting that this index is in-graph, which is not the most efficient, especially if you add to the index as you add your nodes to the database (causing index nodes to be scattered across the disk with data nodes). The consequence of this is that index searches that reach a reasonable percentage of data nodes are likely to cause most of the database to page into ram. There are two workarounds to this:

* Allocate enough ram to allow the entire database to be paged in without page faults.
* Re-import in a way to keep the index separate. This can be done by first importing all cities, and then indexing them all in a second step, causing the index to be clustered in as few pages as possible, which should help with search performance.

Regarding built-in spatial support, that is indeed planned, but the release schedule is not yet finalized. It will not make 2.3, but hopefully the next, or next-next release after that. We'll try keep people informed as things progress.

At least I can report that the plans are focused on this kind of use case, with distance searches, so that should be well supported, faster and easier.

**Comment by Jempan** [comment]
Thanks @sarmbruster  and @craigtaverner for your quick answer!

Great news about future built-in spatial support!! Buildning social network apps with Neo4j today when most domain objects need a location this is by far the functionality I miss the most. An easy way to migrate existing applications using current spatial support would be very appreciated.

I am afraid I am not fully understand how the spatial index is working under the hood or have time to dig deeper right now :( So there is no way I can rearrange the first query to ask only for users within a distance without touching the cities (which I don´t care about here)? So when the user number is 1000 the cities will be loaded 1000 times!?

Another thing, the distance is given in meters isn´t it? Are the users returned in distance order here? For the future built-in support a very convenient thing would be to get the distance to the point with every returned user so it doesn't need to be recalculated again.

Regarding the two workarounds I really prefer the first one if it is doable since the geo database is very time consuming to rebuild. I have been trying to finetune the config values before but always ended up getting the best performance from the default values. My TotalStoreSize is ~700MB, how much total server RAM would I need on a machine which only runs Neo4j? And what config values should I change to allow the entire database to be paged in?

**Comment by craigtaverner** [comment]
Hi @Jempan,

Perhaps I need to explain the cross product a little more. Your original query was:

    start n=node:geom('withinDistance:[58.0,17.0,50000.0]')
    MATCH user WHERE user:User
    return user LIMIT 100

This is in fact two independent searches, the first is the city lookup using the spatial index, and the second is the user lookup by label. Since you have not connected these two in any way, cypher will understand that you want all possible combinations. Personally I suspect you do not want this. Either you have missed a connection, for example a (n)<-[:LIVES_IN]-(user) pattern, or you do want two separate queries. Here are examples:

    start n=node:geom('withinDistance:[58.0,17.0,50000.0]')
    MATCH (user:User)-[:LIVES_IN]->(n)
    return user LIMIT 100

Or separated:

    start n=node:geom('withinDistance:[58.0,17.0,50000.0]') return n limit 100

    MATCH user WHERE user:User return user LIMIT 100

Your second question was about the units, and I've just checked the code at https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/pipes/GeoPipeline.java#L361, and it specifies units of kilometers. The documentation also mentions the units as kilometers: http://neo4j-contrib.github.io/spatial/#rest-api-find-geometries-within--distance

The future built-in version will default to more usual units (like meters), and later versions allow this to be configurable, hopefully.

Regarding the memory performance tuning, there is a good writeup on the neo4j manual at http://neo4j.com/docs/2.2.3/performance-guide.html. I recommend reading that and trying out what is suggested there first.

**Comment by Jempan** [comment]
Hi @craigtaverner and many thanks again for your answer!! Really hope other people could use this info as well now that I am taking your time..

Wow, I didn't see the kilometer specification but that is wonderful news as it means the query now takes 900 ms instead of 9000 ms. Can't believe I didn't test this before. 

To be clearer I have added all objects with a location (lat/lng) to the spatial layer named geom. For the moment those are cities and users but later it will also be events and places. The cities location are added once but the users locations are updated all the time. The typical use case is to be able to retrieve other users, events and places near a user's current location. 

So my first query really has nothing to do with the cities. I just want to show every user which other users are near them based on their current location (lat/lng). In other words it would be perfect to be able to ask the spatial layer for just one label type but I don't know how to do this and that is why I added MATCH (user:User) to retrieve only nodes with the label "User". Is there any other (better) way to accomplish this without searching through all cities?

**Comment by craigtaverner** [comment]
Thanks @Jempan, now I see what you are after. In the first query you used identifier 'n' for the results from the spatial index, but then you created a new identifier 'user' for the test with labels. You should use the same identifier if you mean to apply the spatial index and the label predicate to the same nodes. For example:

    start n=node:geom('withinDistance:[58.0,17.0,50.0]')
    WHERE n:User
    return n LIMIT 100

There is no cross product issue now, since there is only one identifier for both predicates.

**Comment by Jempan** [comment]
Ah that´s perfect, the query now returns in 300 ms. And I feel very stupid, I really thought I had tried that combination but obviously I didn´t. Anyway, THANKS and good luck with the native support, I really looking forward to that and some easy to grasp documentation/examples :)

**Comment by craigtaverner** [comment]
@Jempan I'm super glad everything worked out and it is now fast enough without having to tune the memory as well, or re-import the spatial data.

You also mentioned needing to upgrade your data to the future version, and at the moment we are expecting to support this with cypher commands, for example a command to query all indexed nodes with the start clause, and then add new properties indexed using the new syntax. Exactly how well this will work (hoe scalable) will need to be seen, but hopefully it covers most users needs, so they do not need to re-import all spatial data.
