### ISSUE TITLE
what mathod can i delete a node from Layer ?

### ISSUE THREAD

**Issue by pangguoming** [neo4j-contrib/spatial#198]
Hello:
i can find the REST method: SpatialPlugin/graphdb/addNodeToLayer, i can use this method to add a node.

what mathod can i delete a node from Layer ?

**Comment by craigtaverner** [comment]
Unfortunately the spatial plugin does not have a deleteLayer method. However, what causes a node to be in a layer is the incoming RTREE_REFERENCE relationship. You could just delete that relationship. However, this could have side effects because the index will not be asked to rebalance. Best to call the delete method on the index. See https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java#L128

**Comment by pangguoming** [comment]
thanks
