### ISSUE TITLE
Upgrading to new version

### ISSUE THREAD

**Issue by lordmj** [neo4j-contrib/spatial#201]
I know the Spatial version for Neo4j 3.0 is not out yet, but when it is, will I need to rebuild my spatial indexes from 2.2.6 in order to use Spatial in 3.0?

**Comment by craigtaverner** [comment]
What we try to do is keep the indexes compatible between the versions of Neo4j Spatial, that is the 0.15 number. So if the version for neo4j 3.0.0 is 0.15-neo4j-3.0.0, then the indexes should not need to be rebuilt.

It is not clear yet if this will be possible, but I'm optimistic at this point.

**Comment by lordmj** [comment]
I actually meant Neo4J 2.3 not 3.0.  Sorry for the typo.  But I'm hoping that I can upgrade to 2.3 without having to rebuild indexes.

**Comment by craigtaverner** [comment]
I made a trial release for 2.3, but have not tested it properly yet so have not linked to it from the README. But feel free to give it a try and see what you think.

https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.15-neo4j-2.3.0/neo4j-spatial-0.15-neo4j-2.3.0-server-plugin.zip?raw=true

The code is based on 0.15 version of Neo4j Spatial, with only changes to the API between this library and Neo4j itself, and so should not require indexes being rebuilt. However, if you used 0.14 before, you should re-import the data, since there was a change between 0.14 and 0.15.

**Comment by craigtaverner** [comment]
I did a minimal test that the plugin loads on 2.3 using:

```
curl -u neo4j:neo4j http://localhost:7474/db/data/
```
