### ISSUE TITLE
replace findGeometriesInBBox with findGeometriesIntersectingBBox 

### ISSUE THREAD

**Issue by wilkoquak** [neo4j-contrib/spatial#217]
In the current REST API there is only a function for finding all objects with a bounding box (findGeometriesInBBox). This function can be used for finding objects that need to be drawn on a screen when displaying a map. However, when you draw a map of an area you usually want ALL the object that are visible in that area and not only the ones that are completely inside the area. I propose to implement and extra function findGeometriesIntersectingBBox that would do that.

**Comment by Infiniverse** [comment]
Makes sense. I discussed this with the developers a year or so ago. It seems that most folk are only dealing with point data and so don't come up against this issue. We've got a local patch which changes the behaviour of findGeometriesInBBox to do an 'intersection' test instead of 'contains', which seems to me to be the expected behaviour. Having 'findGeometriesIntersectingBBox' makes it explicit, but I fail to see the circumstances in which you wouldn't want the normal behaviour to do this too.

**Comment by Infiniverse** [comment]
This is our local patch:

```
diff --git a/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java b/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java
index 65623a6..61b94fe 100644
--- a/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java
+++ b/src/main/java/org/neo4j/gis/spatial/indexprovider/LayerNodeIndex.java
@@ -258,7 +258,7 @@ public class LayerNodeIndex implements Index<Node>
                 @SuppressWarnings("unchecked")
                                List<Double> coords = (List<Double>) new JSONParser().parse( (String) params );
 
-                List<SpatialDatabaseRecord> res = GeoPipeline.startWithinSearch(
+                List<SpatialDatabaseRecord> res = GeoPipeline.startIntersectSearch(
                         layer,
                         layer.getGeometryFactory().toGeometry(
                                 new Envelope( coords.get( 0 ), coords.get( 1 ),

```

**Comment by craigtaverner** [comment]
I think the original request related to the REST API, and the proposed patch relates to the IndexProvider API. I would like to fix this issue for all API's, but also take into account that we would like to entirely remove the IndexProvider API for the version of Spatial ported to Neo4j 3.0. The reason for this is that the IndexProvider does things differently to all the rest of Neo4j Spatial causing frequent issues, and now with Neo4j 3.0 we have an alternative solution: procedures!

The only reason we used the IndexProvider in Neo4j Spatial before was as a way to get it accessible from Cypher. The procedures available in Cypher in Neo4j 3.0 allow us to provide a much richer interface to Neo4j Spatial without having to make it fake looking like an index (and cause a lot of confusion in the process).

I propose we make sure that the contains and intersects capabilities are supported in the procedures (and possibly the REST API), but not make changes to the IndexProvider (and perhaps even disable it).

Any thoughts on this?

**Comment by craigtaverner** [comment]
Does this commit satisfy the original request?

**Comment by Infiniverse** [comment]
Hi Craig. This sounds sensible, and I think your patch should fulfil the requirements of @wilkoquak.

I've not played with the 3.0 procedure changes yet, but they look like a major step in the right direction, not withstanding that the draft I saw mention on slack in the last few days didn't have a procedure defined for intersection with arbitrary geometry, which is what we are using.

Whilst we're discussing that, I'm still a bit confused as to why we still have to add (and possibly remove) geometry to a spatial index explicitly. The 3.0 version of neo4j spatial still appears to require a very manual approach. Wouldn't it be much better to define a schema based spatial index by specifying which labels should be associated with which layers? That would be much tidier.

**Comment by craigtaverner** [comment]
Hi Josef.

You are completely right that a proper schema index is the ideal solution, and that is in fact the official spatial plan from within Neo Technology. However, that is a complete re-write of a sub-set of spatial capabilities, and as such is not now, and might never be, a replacement for the Spatial library we have here. To try to reduce confusion, I tend to use the terms 'built-in spatial' and 'spatial library' for the two different systems.

The _built-in spatial_ will be an officially supported part of the database itself, will be coded and tested by the core developers to the same standards as the rest of Neo4j. But it will, at least initially, support only point() and distance() functions, and an index optimised for POINT data types only (and a native point data type). I mentioned this future capability in a talk last year. See slide 47 at http://www.slideshare.net/craigtaverner/neo4j-spatial-foocafe-september-2015.

The _spatial library_ we are looking at here is a much more comprehensive set of _spatial data modelling_ features, originally written for embedded use using the Java Core API back inn 2010, 2011. It has not moved forward much since then. It was not originally written to work within Cypher, or the server, and the efforts to support that were incomplete and fragile. It is seen as a community contribution, with partial support from within Neo Technology.

Back in 2014 I was under the impression that Neo4j would get a new spatial capability built-in within that year. Unfortunately, due to re-prioritisation pressures, that has been delayed until 2016/2017, but it is still in the roadmap, still valued, and I'm still optimistic is will happen (just not sure exactly when). In fact 3.0 already ships with the point() and distance() functions working, but the native point type is missing as is the native spatial index, so this is just a first step in that direction. Regardless of the fact that we are delayed on _built-in spatial_, I was always under the impression that there would be a place for the _spatial library_ for a long time, because the built-in spatial was targeting a different set of goals. Since the built-in spatial has been delayed, I think that fact is only emphasised.

People have also expressed concern that if we support the _spatial library_ using procedures in Cypher, we remove the need for the _built-in spatial_. I disagree, because while the spatial library is much more extensive in capabilities, it is not well optimised, and will always have a performance disadvantage to a native index. And it was never designed for highly concurrent and distributed environments, which makes it potentially less stable for larger production deployments. I think it will remain a powerful toolkit for complex spatial capabilities, but will not be the optimal solution for high performance, high scalability, high availability environments. This makes the two solutions somewhat orthogonal.

However, I would like to see some synergy between the two. Where possible I'd love the two systems to share types or support each others types, so that people using both systems will see the spatial library as something of an extension to the build-in spatial. This thinking will never be complete though because of the key differences between the two, and the one you mention is probably the most crucial. The spatial library does not provide what people think of as an index. It provides index-like capabilities within the data model itself. The RTree is part of the spatial data model. This difference will probably be there for a long time.

**Comment by wilkoquak** [comment]
Hi Craig (and Josef),
Thanks for your commit it does satisfy my original request (I'll close the issue). Also thanks for the interesting discussion on the future development of spatial in 3.0. Starting with 'point' data for the built-in spatial functionality does make sense for a Graph database especially in combination with shortest path algorihtms. A next step could be support for rectangles as most spatial indexes work on rectangles anyway leaving the complex operations on the polygons to the application sied.

Looking forward to further developments, Wilko Quak
