### ISSUE TITLE
incorrect readme

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#222]
in the how to import section for command line, it must be java -cp target/classes;target/dependency/... (semicolon instead of colon), see this discussion on Stack Overflow: http://stackoverflow.com/questions/24373773/neo4j-spatial-import-error

**Comment by ehx-v1** [comment]
just thought it should be mentioned because some users did get confused

**Comment by ehx-v1** [comment]
also wanted you to know BatchInserterImpl is no longer available, you have to use BatchInserters.inserter(...) with the same parameters

**Comment by ehx-v1** [comment]
also noticed that constructors for template classes are called like `new Template<>()` but you use `new HashMap<String, String>()` instead of `new HashMap<>()`, not sure if that works

**Comment by craigtaverner** [comment]
The use of ';' instead of ':' as classpath separator is for windows only. On linux and mac you must use a ':'. I have made a comment in the README commenting on this difference. I hope that is sufficient to avoid future confusion.

Regarding the other comments, we have recently started porting to neo4j 3.0 in the master branch. This should hopefully cover all these changes (and a lot more). I will close this issue, but if you see any other discrepancies please feel free to open new issues.
