### ISSUE TITLE
Out of memory for importing OSM data

### ISSUE THREAD

**Issue by themmes** [neo4j-contrib/spatial#273]
Tried to import new-york-latest.osm

```
Fri Sep 30 15:09:59 CEST 2016: Saving node 6797035      (7647.790512152915 node/second)
Fri Sep 30 15:10:01 CEST 2016: Saving node 6797062      (7635.175179448008 node/second)
Fri Sep 30 15:10:02 CEST 2016: Saving node 6797085      (7622.4345955741765 node/second)
Fri Sep 30 15:10:04 CEST 2016: Saving node 6797105      (7609.59687784082 node/second)
Fri Sep 30 15:10:05 CEST 2016: Saving node 6797127      (7597.254667021355 node/second)
Fri Sep 30 15:10:07 CEST 2016: Saving node 6797149      (7584.495475289838 node/second)
Fri Sep 30 15:10:08 CEST 2016: Saving node 6797175      (7572.315027823113 node/second)
Fri Sep 30 15:10:10 CEST 2016: Saving node 6797187      (7559.5527786180755 node/second)
Fri Sep 30 15:10:11 CEST 2016: Saving node 6797202      (7547.364774385247 node/second)
Fri Sep 30 15:10:13 CEST 2016: Saving node 6800228      (7537.943961699661 node/second)
Fri Sep 30 15:10:14 CEST 2016: Saving node 6805357      (7531.565620234224 node/second)
Fri Sep 30 15:10:15 CEST 2016: Saving node 6806935      (7521.2507472152765 node/second)
Fri Sep 30 15:10:17 CEST 2016: Saving node 6815107      (7516.775436688567 node/second)
Fri Sep 30 15:10:19 CEST 2016: Saving node 6825050      (7515.109940022705 node/second)
Fri Sep 30 15:10:20 CEST 2016: Saving node 6834978      (7513.012337428222 node/second)
Fri Sep 30 15:10:22 CEST 2016: Saving node 6839965      (7506.603979617929 node/second)
Fri Sep 30 15:10:25 CEST 2016: Saving node 6839974      (7480.630125180728 node/second)
Fri Sep 30 15:10:26 CEST 2016: Saving node 6841042      (7469.772774423201 node/second)
Fri Sep 30 15:10:28 CEST 2016: Saving node 6842242      (7459.094169640969 node/second)
Fri Sep 30 15:10:29 CEST 2016: Saving node 6844394      (7449.696761244651 node/second)
Fri Sep 30 15:10:31 CEST 2016: Saving node 6844694      (7438.405186794366 node/second)
Fri Sep 30 15:10:32 CEST 2016: Saving node 6844779      (7426.851021998077 node/second)
^C^Z
[1]+  Stopped                 sudo java -cp target/classes:target/dependency/* org.neo4j.gis.spatial.osm.OSMImporter /data/new-york-osm.db new-york-latest.osm
user@neo4j:/opt/spatial$ htop
bash: fork: Cannot allocate memory
user@neo4j:/opt/spatial$ sudo reboot
bash: fork: Cannot allocate memory
user@neo4j:/opt/spatial$
```

Which ended up bricking the entire server. Is there any solution to the importer using this much memory?

Thanks in advance!

**Comment by themmes** [comment]
Tried lowering the commitInterval to 500 instead of 5000, however this did not flush memory any earlier during the process. Still flooded the 2GB memory

**Comment by craigtaverner** [comment]
A suggestion to reduce the chance of bricking the server - set a lower java heap, forcing GC to happen earlier. However, having said that, I think there are some fundamental flaws in the way OSMImporter was written that make it hard to scale on larger OSM files without adding a lot more real RAM to the server. The key problem is that OSM is a tabular format, and when building the graph there is a need to correlated previously imported nodes with new relationships (street segments), and this requires a way to lookup nodes by their OSM id's. The current approach issues lucene indexes and hash tables, and requires memory.

In the last couple of years there has been a new high performance data importer tool for Neo4j, that is very good at this exact kind of problem, but the OSMImporter has not been ported to that system because it requires a substantial re-write. Until that is done, the only real solution is to add more RAM. This will get you further, but not remove the ceiling.

**Comment by ehx-v1** [comment]
How about putting a couple of `System.gc()`? Sure, it's quite bad practice to call it manually, but as a workaround it might work.

**Comment by themmes** [comment]
Thanks for your reactions, sorry it took so long for me to reply to them.

For now I am avoiding the OSMImporter by using an in-between conversion of .osm to graphml. Still the tool to perform this operation requires loads of RAM, but I can more freely tune this to my limitations. Also the graphml format provides me with more freedom to use any graphdb.

**Comment by craigtaverner** [comment]
Have you tried the new OSMImporter tool that I wrote last year that uses the parallel batch importer framework I described in my previous reply (I replied in 2016, and wrote the new tool in 2018). Have a look at https://github.com/neo4j-contrib/osm

That tool should have the abiluty to import MUCH larger OSM files without running out of memory. The largest I tried was the entire planet, and it ran until it filled my 4TB disk before stopping. I'll try again with more disk space, but in principle it should be possible to import the planet now.
