### ISSUE TITLE
Geometries on Relations !?!

### ISSUE THREAD

**Issue by MobiusF** [neo4j-contrib/spatial#274]
Hi,

How much effort would it be to allow relation properties to be added to a spatial index?

Would this fit in the current architecture?

BR,

M

**Comment by craigtaverner** [comment]
Unfortunately the current architecture requires adding a relationship link from the geometry node to the RTree in-graph index structure. The assumption that there is always a single node representing a geometry is throughout the design. Even for cases where the geometry object is itself a complex graph of nodes and relationships, we still pick one node as the point to link to the RTree.

On a different point, in Neo4j itself there are plans to add `Point` types as properties of nodes (and presumably relationships). There too, the plan is to add an index (much like the schema index introduced in 2.0) for indexing nodes by their properties. Indexing relationships by properties is not supported in Neo4j using schema indexes. Presumably if that does get supported one day, then geometries on relationships would get that support too.

**Comment by craigtaverner** [comment]
In a way, this question is related to questions about the support for hypergraphs in neo4j (edges to edges, or relationships between more than two nodes). I think that is unlikely to ever be supported as a concept in neo4j, because it is always easy enough to model the hyper-edge with an intermediate node.

In your case you would also need to add an intermediate node to hold the geometry.
