### ISSUE TITLE
Support 3.1.0

### ISSUE THREAD

**Issue by tuddman** [neo4j-contrib/spatial#288]
trying to load spatial procedures in `3.1.0` :

`call spatial.procedures()`

`Failed to invoke procedure `spatial.procedures`: Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.impl.proc.Procedures.getAll()Ljava/util/Set;`

**Comment by tuddman** [comment]
apologies. filed erroneously.

a call to `call spatial.procedures()` results in the above error, which was **not** the case with `3.0.7` 

a call to `call dbms.procedures()`  lists the spatial functions, and 

a call to `call spatial.addPointLayer('layerName')` works as advertised.

**Comment by craigtaverner** [comment]
The spatial project has not yet been ported to Neo4j 3.1. It is nice that you were able to get it to work, at least partially, on 3.1. We will, hopefully soon, port it and make sure all parts work correctly.

**Comment by tuddman** [comment]
yes, I haven't yet tested the full functionality of spatial on `3.1.0`  but some basic `addNodeToLayer` and distance-based `CALL spatial.getWithinDistance(...)` queries appear to work fine.

out of interest, what all is involved to port from `3.0.x` to `3.1.x`     sorry I'm not close enough to the neo4j core to know how procedures may be affected.

**Comment by craigtaverner** [comment]
@tuddman To port to 3.1 you edit the pom.xml and change the dependency on neo4j (edit the neo4j.version property) and then recompile and run all tests. Fix all compile errors and fix all tests to pass. Hopefully it is not much work, but since I have not tried myself, I don't know if it will be trivial or hard. Knowledge of what has changed between Neo4j 3.0 and 3.1 will help in fixing compile and test errors.
