### ISSUE TITLE
Add node to layer

### ISSUE THREAD

**Issue by m007** [neo4j-contrib/spatial#295]
After importing an OSM layer via procedure call `CALL spatial.importOSM('/tmp/file.osm');` I want to add new nodes to this layer. I tried something like

    CREATE (n {lon: 6.3740429666, lat: 50.93676351666}) WITH n CALL spatial.addNode('file.osm', n) YIELD node RETURN node;

but that results in 

    Failed to invoke procedure `spatial.addNode`: Caused by: org.neo4j.gis.spatial.osm.OSMGeometryEncoder$OSMGraphException: Failed to decode OSM geometry: null

I did not find an example of how to add a node to an OSMLayer in the unit tests of the project. Does it work at all? And how?

**Comment by m007** [comment]
I solved that issue myself. Adding a node to the OSM layer results in `DefaultLayer.add` being called

```java
    public SpatialDatabaseRecord add(Node geomNode) {
    	Geometry geometry = getGeometryEncoder().decodeGeometry(geomNode);     
    	
    	// add BBOX to Node if it's missing
    	getGeometryEncoder().encodeGeometry(geometry, geomNode);
    	
        index.add(geomNode);
        return new SpatialDatabaseRecord(this, geomNode, geometry);
    }
```

## Problem

There `getGeometryEncoder().decodeGeometry(geomNode);` will call OSMGeometryEncoder.decodeGeometry:

```java
    public Geometry decodeGeometry(PropertyContainer container) {
		Node geomNode = testIsNode(container);
		try {
			GeometryFactory geomFactory = layer.getGeometryFactory();
			Node osmNode = getOSMNodeFromGeometryNode(geomNode);
			if (osmNode.hasProperty("node_osm_id")) {
				return geomFactory.createPoint(new Coordinate((Double) osmNode.getProperty("lon", 0.0), (Double) osmNode
						.getProperty("lat", 0.0)));
			} else if (osmNode.hasProperty("way_osm_id")) {
				int vertices = (Integer) geomNode.getProperty("vertices");
				int gtype = (Integer) geomNode.getProperty(PROP_TYPE);
				return decodeGeometryFromWay(osmNode, gtype, vertices, geomFactory);
			} else {
				int gtype = (Integer) geomNode.getProperty(PROP_TYPE);
				return decodeGeometryFromRelation(osmNode, gtype, geomFactory);
			}
		} catch (Exception e) {
			throw new OSMGraphException("Failed to decode OSM geometry: " + e.getMessage(), e);
		}
	}
```

what will call `getOSMNodeFromGeometryNode(geomNode);`:

```java
	public static Node getOSMNodeFromGeometryNode(Node geomNode) {
		return geomNode.getSingleRelationship(OSMRelation.GEOM, Direction.INCOMING).getStartNode();
	}
```

In  `getOSMNodeFromGeometryNode(geomNode);` a `NullPointer` will be thrown since `geomNode.getSingleRelationship(OSMRelation.GEOM, Direction.INCOMING)` will be `null` when adding a new node to the layer (a new node, by its very defintion, has no relationship to the rest of the graph).

## Solution

Changing that above method into

```java
    public static Node getOSMNodeFromGeometryNode(Node geomNode) {
	        Relationship singleRelationship = geomNode.getSingleRelationship(OSMRelation.GEOM, Direction.INCOMING);
		/*
		 * Newly added nodes may not have this incoming relationship.
		 * We'll return the geomNode itself then.
		 */
	        return singleRelationship == null ? geomNode : singleRelationship.getStartNode();
	}
```

will avoid the `NullPointer` being thrown in that case. Additionally changing `getGeometryEncoder().decodeGeometry(geomNode);` to 

```java
    public Geometry decodeGeometry(PropertyContainer container) {
		Node geomNode = testIsNode(container);
		try {
			GeometryFactory geomFactory = layer.getGeometryFactory();
			Node osmNode = getOSMNodeFromGeometryNode(geomNode);
			if (osmNode.hasProperty("node_osm_id")) {
				return geomFactory.createPoint(new Coordinate((Double) osmNode.getProperty("lon", 0.0), (Double) osmNode
						.getProperty("lat", 0.0)));
			} else if (osmNode.hasProperty("way_osm_id")) {
				int vertices = (Integer) geomNode.getProperty("vertices");
				int gtype = (Integer) geomNode.getProperty(PROP_TYPE);
				return decodeGeometryFromWay(osmNode, gtype, vertices, geomFactory);
			} else {
				/*
				 * We expect nodes that should be added to the layer to not have
				 * the PROP_TYPE property, but to provide the necessary lon and lat
				 * values for creating a geographic point.
				 */
				if (!geomNode.hasProperty(PROP_TYPE)) {
					Object longitude = geomNode.getProperty("lon", 0.0);
					Object latitude = geomNode.getProperty("lat", 0.0);
					/*
					 * lon, lat values which can be represented with integers
					 * (like 1, 2 or 60) will be stored as Long, whereas others
					 * (like 1.1, 2.78 or 50.78965453121) will be stored as Double,
					 * so we have to carefully examine that situation heere:
					 */
					double dLongitude = longitude instanceof Double ? (Double) longitude : (Long) longitude;
					double dLatitude = latitude instanceof Double ? (Double) latitude : (Long) latitude;
					return geomFactory.createPoint(new Coordinate(dLongitude, dLatitude));
				}
				int gtype = (Integer) geomNode.getProperty(PROP_TYPE);
				return decodeGeometryFromRelation(osmNode, gtype, geomFactory);
			}
		} catch (Exception e) {
			throw new OSMGraphException("Failed to decode OSM geometry: " + e.getMessage(), e);
		}
	}
```

enables adding a node to the layer. The changes to the code are further explained in the comments.
I implemented this solution here: https://github.com/m007/spatial/commit/c1e9e9c15467e46f8e472c6a6f3b2b6f6a2bbcac.

**Comment by craigtaverner** [comment]
Interesting solution. I have some problems with it, however. The reason for the missing relationship is not that the node is not yet added to the graph, but rather that the node does not conform to the data model of OSM. The original OSM data was added using the OSMImporter class which builds a fully connected graph structure to maintain the connected nature of the OSM data. The OSMGeometryEncoded respects this. It is possible to add disconnected nodes to the model, but they still need to maintain the model of the rest of OSM. The key element missing is that in all of the OSM model the node with the latitude and longitude values is not the geometry node. This is because OSM supports much more complex geometries than points, but the RTree index expects a single representative geometry node to index. This geometry node will contain only the gtype and the bbox, and then have a relationship to one or more nodes with actual lat/long values (one for points, more for other types).

The call you made with `CREATE (n {lon: 6.3740429666, lat: 50.93676351666}) WITH n CALL spatial.addNode('file.osm', n) YIELD node RETURN node;` attempts to create just an OSM point node, not an OSM geometry node. You would need something more like:

    CREATE (n {lon: 6.3740429666, lat: 50.93676351666})-[:GEOM]->(g {gtype:1,bbox:[...]} WITH g CALL spatial.addNode('file.osm', g) YIELD node RETURN node;

I've not tested this, but it might be best to leave the encoding to the OSMGeometryEncoding, and instead add the node like this:

    CALL spatial.addWKT('file.osm', 'POINT(6.3740429666 50.93676351666)')

This way, the OSM node and the geometry node should both be made for you with the correct relationships between them.

**Comment by craigtaverner** [comment]
I added a test to the library to verify that my last suggestion works. Take a look at the test code at https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L513
