### ISSUE TITLE
Cypher withinDistance fails with higher precision latitude/longitude

### ISSUE THREAD

**Issue by Xenopathic** [neo4j-contrib/spatial#298]
I'm experiencing issues with the `spatial.withinDistance()` procedure, which does not return nodes correctly when their latitude/longitude is specified to a certain precision. It's easiest to just demonstrate what happens:

```
call spatial.addPointLayer("bar");
create (n:Point) set n={latitude: 52.2029252, longitude: 0.0905302} with n call spatial.addNode("bar", n) yield node return node;
create (n:Point) set n={latitude: 52.202925, longitude: 0.090530} with n call spatial.addNode("bar", n) yield node return node;

call spatial.withinDistance("bar", {latitude:52.2029252,longitude:0.0905302}, 100);
# notice only one node is returned, the one with the lower precision

call spatial.withinDistance("bar", {latitude:52.202925,longitude:0.0905302}, 100);
# notice both nodes are returned
```

I am using Neo4j 3.0.3 with Spatial 0.19 installed.

The larger precision of number is what the Java `double` type becomes when using Neo4j OGM, which is how I came across the issue. Is there some fix, or failing that a quick workaround, that would enable this workflow to work?

**Comment by craigtaverner** [comment]
There was a numerical overflow bug in the distance calculation that lead to NaN results for points extremely close to each other due to Math.acos(x) not allowing x>1.0, and in your case you got x=1.00000000001 (or some such). I've fixed this in https://github.com/neo4j-contrib/spatial/commit/539e5d4da82f4f900d3fc8e6399c99bc43c0b22c

So it should come out in the next release.

**Comment by Xenopathic** [comment]
I can confirm that this has fixed the issue, thanks!
