### ISSUE TITLE
delete nodes

### ISSUE THREAD

**Issue by vvavepacket** [neo4j-contrib/spatial#319]
Is it enough to remove spatial nodes thru this query. Are we missing something if we use this query?

> MATCH(n:Spatial) DETACH DELETE N;

Or should we stick to the spatial procedures?

**Comment by craigtaverner** [comment]
In principle, it is better to stick with the procedures, but in reality, they are just editing the graph much like you are. However, since you might be unaware of changes in the way the library structures the spatial graph, it is safer to use the procedures since they should correct deal with these changes. If, however, you know the graph model very well, then doing it with Cypher can work. Note that you will need to review the graph model after any new release of Neo4j Spatial, as that might require you to change your Cypher.
