### ISSUE TITLE
ReadMe Importing OSM file section needs a update

### ISSUE THREAD

**Issue by VishwaShanika** [neo4j-contrib/spatial#331]
It seems BatchInserterImpl is no longer using. But readme using it within example

**Comment by craigtaverner** [comment]
I've taken a look and it seems the README used a very old version of code for creating the BatchInserter. Instead of `new BatchInserterImpl(dir,config)` you need `BatchInserters.inserter(new File(dir), config)`. I've updated the README. I should also mention that there is a new project for much faster import of OSM data at https://github.com/neo4j-contrib/osm. It is standalone and does not yet work with 'Neo4j Spatial', but I hope to make it the default way of importing data for Neo4j Spatial OSM models also.
