### ISSUE TITLE
Some problems about Neo4j-Spatial

### ISSUE THREAD

**Issue by WuChengbin** [neo4j-contrib/spatial#335]
I tried to import the shp file using the org.neo4j.gis.spatial.ShapefileImporter method.
There are about 15000 shp files(contain millions of geometry nodes) per year, but I found it was very slow to import them, especially after importing about 2000 files.
Is there a solution, or other ways to import such many data?
I appreciate it if there is any solution.
@craigtaverner 
And one more question, I found some procedures such as:
spatial.bbox(layerName :: STRING?, min :: ANY?, max :: ANY?) :: (node :: NODE?)
What is the parameter type ANY?
When I call this procedure, what parameters should I input?
Can you give me an example?Thx!

**Comment by craigtaverner** [comment]
Hi @WuChengbin.

The `:ANY` type was used because it is possible to pass in the points using many different types. We support JTS Geometry, Neo4j Geometry (Point), Node and Map. The last two require properties with names 'latitude' and 'longitude'.

I do not know why your shapefile importer is slow, but do know that the original code was developed based on relatively small datasets. I'm reviewing the code now and also see that it does not make use of the newer RTree Bulk Insert capabilities we added in 2016.

You could probably change it to do that if you look at line 221 and move it down to 231 and call the method to add many geometries at the same time. I've not had a chance to try that out myself. Let me know how it goes.

**Comment by WuChengbin** [comment]
Does it means move the cod on line 221 to line 231 in ShapefileImpoter.java? And which method should I call to add geometries at the smae time? @craigtaverner
