### ISSUE TITLE
from witch version i can use point

### ISSUE THREAD

**Issue by HADDADENICAR** [neo4j-contrib/spatial#342]
from witch verison i can use the point() type function with your plugin ?

**Comment by craigtaverner** [comment]
It depends on exactly how you use `point()`. That function was released in Neo4j 3.0, and the spatial library for 3.0 got some procedures for working with spatial data in 3.0, and some partial compatibility with the `point()` function. This stayed about the same for 3.0 to 3.3, but in 3.4 things have changed a bit because 3.4 improved the support for `point()` and the spatial library needed to change a bit because of that.

If this does not answer your question, please ask again with more specific details about what you mean, or how you want to use both the built-in `point()` function and the spatial plugin.
