### ISSUE TITLE
plot R-tree in a map

### ISSUE THREAD

**Issue by HADDADENICAR** [neo4j-contrib/spatial#343]
**I m using neo4j server**.
I 'am new to neo4j and newer to its spatial plugin.
Recently i was able to create an R-tree of NYC Cabs locations(pickup and drop-off) and some relationships between them (trip relationship) as well the Time Location Relationships with time nodes.

my question is : is it possible to plot this R-tree in a map ?
![r-tree photo](https://i.stack.imgur.com/nYcU3.png)

**Comment by craigtaverner** [comment]
I'm not sure what you mean by "plot this R-tree in a map"? An RTree is an index. So the normal view of it is a tree view. Or perhaps you mean you would like to plot the tiles like in the image near the top of the page at https://en.wikipedia.org/wiki/R-tree? We actually have some image printing code in the spatial library for printing the image of the tiles like that, if it is what you are after.

If instead, you mean you want to map a map application with your NYC cab locations on a background map, there are many solutions. The library includes a geotools DataSource implementation so that you can include it in a GeoTools enabled GIS like uDIG or GeoServer, and view it there.

Alternatively, you can create a web map using leaflet and mapbox and just access a Neo4j Server remotely and plot the points there. For this option, you do not need Neo4j Spatial at all, and could just use the built-in point and point-index support in Neo4j 3.4.
