### ISSUE TITLE
plugin not loading in installation

### ISSUE THREAD

**Issue by gchokeen** [neo4j-contrib/spatial#344]
Hi, 
I want find the nodes that's close to my location (lat,lng) like nearby search. So I was thinking to use the spatial plugin. I created a build in my local machine and upload in the Ubuntu server at this location /var/lib/neo4j/plugins/neo4j-spatial-0.25.5-neo4j-3.4.1-server-plugin.jar and then restarted my neo4j server (3.4.0).

I can't find the spatial plugin information when I check in /db/data folder. So I just tried running this query to check the output but I got some error

```START n=node:geom('withinDistance:[60.0, 15.0, 500.0]') return n;```

> Neo.ClientError.Schema.IndexNotFound: Index `geom` does not exist

So plugin is not installed properly or do I need to do something specially to create geom index?

I already have lat, lng information on node "Store".

Can someone suggest me how to get it done correctly?

Thanks
Gowri

**Comment by craigtaverner** [comment]
The `START` clause for accessing the spatial features was dropped when we upgraded to Neo4j 3.0 a few years ago. Since then the main way to access spatial is using procedures. If you run `CALL dbms.procedures`  you will see which procedures are available. All those starting with `spatial` come from the plugin.

However, I can also say that your use case sounds like something that does not need the spatial plugin at all. Starting at 3.0, and much improved in 3.4, are the `point` and `distance` functions built into Neo4j itself. In 3.4 these are also backed by an index to make spatial distance searches fast over even large datasets.

There are quite a few blogs on this. One recent on is at https://medium.com/neo4j/working-with-neo4j-date-and-spatial-types-in-a-react-js-app-5475b5042b50

Also, the Neo4j documentation includes details on this feature. See https://neo4j.com/docs/developer-manual/current/cypher/syntax/spatial/

**Comment by gchokeen** [comment]
@craigtaverner : Thank you for showing a light, it worked well
