### ISSUE TITLE
problems with imported osm file

### ISSUE THREAD

**Issue by wyrobekj** [neo4j-contrib/spatial#349]
I have the following problems with the plugin and importing. 
(1) I am unable to succesfully compile the plugin on my computer - it returns errors on tests, layers are not correctly imported
(2) when I am using a pre-compiled plugin, still, when importing I do not receive layers
(3) as far as I can tell, plugin does not import lines and polygons
(4) many objects, like lakes or streets, do not have coordinates, some have bounding boxes  and they are represented as points
(5) in order to use spatial functions I need to create a named index. I browsed the internet as much as I could, did not find any example how to create a named index
(6) I think that at the time being, I am unable to calculate on imported data lengths of the streets or area of the lakes or forests.

**Comment by craigtaverner** [comment]
@wyrobekj In order to give you help or advice I would need to know exactly what you are trying to do, and what versions of Neo4j and 'Neo4j Spatial' you are working with, and what data files you are trying to import and how you are trying to import them.

Also, if you are getting compile errors, please include the error itself, so we can figure out what is going wrong. Also, which branch you are compiling and what OS you are using and Java version and Maven version?

**Comment by craigtaverner** [comment]
This issue does not have enough information to reproduce, and there has been no response to my questions in six months.
