### ISSUE TITLE
Server Plugins are depcreated

### ISSUE THREAD

**Issue by stevenleadbeater** [neo4j-contrib/spatial#364]
The Neo4J server plugin API has been deprecated for some time and removed in the current master for the server-api itself scheduled for release with 4.0. The plugin will need to be migrated to an unmanaged extension if it is to be compatible with the new version of Neo:

1/ Unmanaged Server Extensions documentation: https://neo4j.com/docs/java-reference/current/extending-neo4j/http-server-extensions/
2/ Commit removing current dependency: https://github.com/neo4j/neo4j/commit/d95daad162d01eadf186d93c3c815be7b9e04689#diff-35cb3e52a564d5e0af5ac10661ec73c7

**Comment by craigtaverner** [comment]
The original reason for the ServerPlugin code was for use in Neo4j 1.x and 2.x where we had no procedures, and the only remote surface for accessing the library was the REST API. However, since we ported to Neo4j 3.0, we also removed the REST API, and the ServerPlugin code is no longer of any use. I think it will naturally be removed as part of the port to Neo4j 4.0. When that will happen is anyones guess, of course, since this library is supported largely on a volunteer basis. I hope to give it a try soon. Feel free to help out :-)

**Comment by craigtaverner** [comment]
I finished the first draft of a port to Neo4j 4.0, 4.1 and 4.2. In this, the last vestigates of the REST API were entirely removed. As mentioned before, I believe the Cypher procedures are a rich surface than the REST API ever was, so I think this was the right direction to move.
