### ISSUE TITLE
Will it be technically possible to port to Neo4j 4.0

### ISSUE THREAD

**Issue by MobiusF** [neo4j-contrib/spatial#372]
Craig, 

Is it technally possible to port your plugin to 4.0 or are the internal differences to big?

BR,

M.

**Comment by craigtaverner** [comment]
It is technically possible. I tried this earlier this year, and was blocked by the removal of support for 'explicit indexes' in Neo4j 4.0. We use them in a few places for backing the space-filling-curves, as well as for importing OSM data. We would need to find alternatives to do this instead. I think perhaps two different options for the two features:

* Perhaps access lucene directly for the space-filling curves
* Use the same underlying memory tables that the neo4j import tool uses for the OSM import (perhaps just port to the newer OSM library that I wrote, but that looses some features)

I'm not sure when I will have time to work on this again, but would be happy to advise or mentor someone else if they are interested in giving it a go. Otherwise you'll just have to wait until I get a chance.

**Comment by craigtaverner** [comment]
I have recently been working on porting Neo4j Spatial to Neo4j 4.x. This was a major undertaking because many old deprecated API's were removed in Neo4j 4.x, and since the spatial library was originally built for Neo4j 1.x, it was heavily dependent on those API's. In fact some very deep refactoring needed to be done to get this port completed. As such I consider this work as quite experimental. Since it currently passes all existing tests, I wanted to make releases so that people could try it out and see if it works for them, and let me know if there are issues. Please also read the release notes on the release pages for these releases to fully understand the extent of the changes. Some things are not backwards compatible, and in addition there are new security implications in the way I managed to keep backwards compatibility for cases where it would not normally be possible.

• https://github.com/neo4j-contrib/spatial/releases/tag/0.27.0-neo4j-4.0.3 contains a description of the largest changes required to port to Neo4j 4.x
• https://github.com/neo4j-contrib/spatial/releases/tag/0.27.1-neo4j-4.1.7 some smaller changes required to support 4.1
• https://github.com/neo4j-contrib/spatial/releases/tag/0.27.2-neo4j-4.2.3 a few more smaller changes to support 4.2
