### ISSUE TITLE
importShapefile error

### ISSUE THREAD

**Issue by v2belleville** [neo4j-contrib/spatial#373]
Hello,

when trying to import shape file I get errors that prevent loading the file

polygons :
![image](https://user-images.githubusercontent.com/8779004/97920878-6abd8700-1d5a-11eb-874d-14b72c32213d.png)

points :
![image](https://user-images.githubusercontent.com/8779004/97920988-93de1780-1d5a-11eb-8d1f-422bcf8b0b52.png)

Attached are the log for a test db in 3.5.20 
[neo4j.log](https://github.com/neo4j-contrib/spatial/files/5478128/neo4j.log)
[debug.log](https://github.com/neo4j-contrib/spatial/files/5478129/debug.log)

**Comment by craigtaverner** [comment]
Could you provide sample data for this, as my test data does not show this error.

**Comment by galtay** [comment]
Hi, I'm having the same issue using a census shape file. 
https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_01_puma10_500k.zip

**Comment by galtay** [comment]
by setting 

`JAVA_HOME==/usr/lib/jvm`

I was able to get a new error which is progress! 

> Failed to invoke procedure `spatial.importShapefile`: Caused by: java.lang.IllegalArgumentException: org.geotools.styling.StyleFactory is not an ImageIO SPI class

**Comment by galtay** [comment]
OK, downgraded from java 11 to java 8 and now this seems to be working. This is a useful tool on ubuntu 
`sudo update-alternatives --config java`

**Comment by craigtaverner** [comment]
Thanks, @galtay, I just noticed this error for the first time last week when I inadvertently tried to run with java11. Since Neo4j Spatial only currently supports Neo4j 3.x, and Neo4j 3.x are still built using Java8, we are stuck with Java8 for now.

This particular error seems to be a symptom of geotools libraries not supporting newer Java, at least the versions of Geotools that spatial uses. I have been looking into porting spatial to neo4j 4.x, and java 11, and it looks to be a massive job due to the way transactions are handled in Neo4j 4.x. Once I've solved that, I will also need to upgrade geotools to get passed this error.
